server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url:
    username:
    password:

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:com/zero/blogbackend/mapper/**/*.xml

cos:
  secretId:
  secretKey:
  reginName:
  bucketName:
  prefix: