server:
  port: 8080

spring:
  datasource:
    url:
    username:
    password:

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0